import { IJobAdd } from "../src/components/JobAdd";

export const jobs: Array<IJobAdd> = [
  {
    company: "Lyft",
    role: "Software Engineer Grad",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1659312000000,
    type: "grad",
    location: "Sydney - Australia",
  },
  {
    company: "Uber",
    role: "Software Engineer Intern",
    tags: ["remote", "managing", "saas"],
    logo: "companyLogo",
    posted: 1662078009000,
    type: "intern",
    location: "Melbourne - Australia",
  },
  {
    company: "Tesla",
    role: "CEO Intern",
    tags: ["hybrid", "react", "saas"],
    logo: "companyLogo",
    posted: 1662085209000,
    type: "intern",
    location: "Melbourne - Australia",
  },
  {
    company: "Lyft",
    role: "Software Engineer Intern",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1659406809000,
    type: "intern",
    location: "Perth - Australia",
  },
  {
    company: "Lyft",
    role: "Software Engineer Grad",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1660962009000,
    type: "grad",
    location: "Perth - Australia",
  },
  {
    company: "Lyft",
    role: "Software Engineer Grad",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1661134809000,
    type: "grad",
    location: "Sydney - Australia",
  },
  {
    company: "Uber",
    role: "Software Engineer Intern",
    tags: ["remote", "managing", "saas"],
    logo: "companyLogo",
    posted: 1661480409000,
    type: "intern",
    location: "Remote - Australia",
  },
  {
    company: "CSE Gigs",
    role: "Intern",
    tags: ["hybrid", "react", "saas"],
    logo: "companyLogo",
    posted: 1661473209000,
    type: "intern",
    location: "Remote - Australia",
  },
  {
    company: "Microsoft",
    role: "Software Engineer Intern",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1661127609000,
    type: "intern",
    location: "Remote - Australia",
  },
  {
    company: "Lyft",
    role: "Software Engineer Intern",
    tags: ["remote", "react", "saas"],
    logo: "companyLogo",
    posted: 1661138409000,
    type: "intern",
    location: "Remote - Australia",
  },
];
