import type { NextPage } from "next";
import Head from "next/head";
import JobAdd, { IJobAdd } from "../components/JobAdd";
import { trpc } from "../utils/trpc";
import companyLogo from "../../public/companies/Microsoft.png";
import Stats from "../components/stats";
import EmailSubscription from "../components/EmailSubscription";
const jobs: Array<IJobAdd> = [
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Uber",
    role: "Software Engineer Manager",
    tags: ["remote", "managing", "saas"],
    logo: companyLogo,
  },
  {
    company: "Tesla",
    role: "CEO",
    tags: ["hybrid", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Uber",
    role: "Software Engineer Manager",
    tags: ["remote", "managing", "saas"],
    logo: companyLogo,
  },
  {
    company: "Tesla",
    role: "CEO",
    tags: ["hybrid", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
  {
    company: "Lyft",
    role: "Software Engineer",
    tags: ["remote", "react", "saas"],
    logo: companyLogo,
  },
];

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <div className="bg-stone-100">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 ">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          CSE <span className="text-purple-300">Gigs</span>
        </h1>
        <Stats />
        <div className="grid gap-4 pt-6 text-center md:grid-cols-1 lg:w-3/4">
          {jobs.map((job, idx) => (
            <JobAdd
              company={job.company}
              role={job.role}
              tags={job.tags}
              logo={job.logo}
              key={idx}
            />
          ))}
        </div>
        {/* <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> */}
        <EmailSubscription />
      </main>
    </div>
  );
};

export default Home;
